name: pylint
on:
  push:
  pull_request:
jobs:
  run_pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.x]
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: install pylint
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: install requirements
      run: |
        test -f requirements.txt && pip install -r requirements.txt || :
    - name: run pylint
      shell: sh
      run: |
        find . -name '*.py' -print0 | xargs --null --no-run-if-empty pylint
